-- ADR 0100 decision 2 / epic #398: the curated IFRS crosswalk
-- (fundamentals/extraction/ifrs_crosswalk.rs) is now the naming authority
-- for the ESEF/iXBRL path. This seeds a canonical kpi_definitions row for
-- every crosswalk metric_key that has none yet -- 87 new keys, mostly
-- balance-sheet/income-statement/cash-flow lines observed at >=3 of the 8
-- sampled GPW filings (ifrs-crosswalk-candidates.txt) with no existing
-- catalog equivalent (reuse-before-mint already resolved the rest onto
-- pre-existing keys: wdf_equity_parent, wdf_net_profit_parent,
-- wdf_pretax_profit, wdf_share_capital, wdf_noncurrent_assets,
-- wdf_noncurrent_liabilities, wdf_net_cash_change, inventories,
-- dividend_per_share, capex, interest_expense -- none of those are
-- inserted here, they already have a seeded definition).
--
-- origin/statement_group/period_nature are set explicitly AT INSERT (the
-- 0129/0130/0141 convention: those backfills are one-shot and never revisit
-- a later row). INSERT OR IGNORE on stable bare canonical ids
-- (kpidef_<metric_key>) so a re-run, or a key that later gains a curated
-- override, is never clobbered.
--
-- This is a NAMING seed only: it does not populate financial_facts, change
-- esef::parse_esef/concept_to_metric_key, or wire the crosswalk into any
-- read/write path -- that is the Layer 1 -> Layer 2 projection, the next
-- slice of this epic.

INSERT OR IGNORE INTO kpi_definitions
    (id, scope, metric_key, label, value_kind, unit, computation, formula, origin, statement_group, period_nature) VALUES
('kpidef_adj_change_in_inventories', 'canonical', 'adj_change_in_inventories',
 'Adjustment — change in inventories', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_change_in_trade_payables', 'canonical', 'adj_change_in_trade_payables',
 'Adjustment — change in trade and other payables', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_change_in_trade_receivables', 'canonical', 'adj_change_in_trade_receivables',
 'Adjustment — change in trade and other receivables', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_depreciation_and_amortisation', 'canonical', 'adj_depreciation_and_amortisation',
 'Adjustment — depreciation and amortisation', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_income_tax_expense', 'canonical', 'adj_income_tax_expense',
 'Adjustment — income tax expense', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_losses_gains_on_disposal_of_noncurrent_assets', 'canonical', 'adj_losses_gains_on_disposal_of_noncurrent_assets',
 'Adjustment — losses/gains on disposal of non-current assets', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_unrealised_fx_losses_gains', 'canonical', 'adj_unrealised_fx_losses_gains',
 'Adjustment — unrealised FX losses/gains', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adjustments_to_reconcile_profit_loss', 'canonical', 'adjustments_to_reconcile_profit_loss',
 'Adjustments to reconcile profit/loss', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_administrative_expense', 'canonical', 'administrative_expense',
 'Administrative expense', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_cash_flows_from_operations', 'canonical', 'cash_flows_from_operations',
 'Cash flows from operations (before working capital)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_cash_per_cash_flow_statement', 'canonical', 'cash_per_cash_flow_statement',
 'Cash and equivalents (cash flow statement)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'instant'),
('kpidef_cash_used_in_business_acquisitions', 'canonical', 'cash_used_in_business_acquisitions',
 'Cash used in business acquisitions', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_comprehensive_income_attributable_nci', 'canonical', 'comprehensive_income_attributable_nci',
 'Comprehensive income attributable to NCI', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_comprehensive_income_attributable_parent', 'canonical', 'comprehensive_income_attributable_parent',
 'Comprehensive income attributable to parent', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_cost_of_sales', 'canonical', 'cost_of_sales',
 'Cost of sales', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_current_lease_liabilities', 'canonical', 'current_lease_liabilities',
 'Current lease liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_provisions_employee_benefits', 'canonical', 'current_provisions_employee_benefits',
 'Current provisions for employee benefits', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_tax_assets', 'canonical', 'current_tax_assets',
 'Current tax assets', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_tax_liabilities', 'canonical', 'current_tax_liabilities',
 'Current tax liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_trade_receivables', 'canonical', 'current_trade_receivables',
 'Current trade receivables', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_deferred_tax_assets', 'canonical', 'deferred_tax_assets',
 'Deferred tax assets', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_deferred_tax_liabilities', 'canonical', 'deferred_tax_liabilities',
 'Deferred tax liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_dividends_paid', 'canonical', 'dividends_paid',
 'Dividends paid', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_dividends_paid_financing_activities', 'canonical', 'dividends_paid_financing_activities',
 'Dividends paid (financing activities)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_dividends_paid_to_owners_of_parent_financing', 'canonical', 'dividends_paid_to_owners_of_parent_financing',
 'Dividends paid to owners of parent (financing activities)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_eps_basic_continuing', 'canonical', 'eps_basic_continuing',
 'EPS (basic, continuing operations)', 'monetary', NULL, 'reported', NULL, 'seed', 'per_share', 'duration'),
('kpidef_eps_diluted_continuing', 'canonical', 'eps_diluted_continuing',
 'EPS (diluted, continuing operations)', 'monetary', NULL, 'reported', NULL, 'seed', 'per_share', 'duration'),
('kpidef_equity_changes_in_ownership_interests_in_subsidiaries', 'canonical', 'equity_changes_in_ownership_interests_in_subsidiaries',
 'Equity — changes in ownership interests in subsidiaries', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_equity_other_transfers', 'canonical', 'equity_other_transfers',
 'Other equity transfers', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_equity_sharebased_payment_transactions', 'canonical', 'equity_sharebased_payment_transactions',
 'Equity — share-based payment transactions', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_fee_commission_expense', 'canonical', 'fee_commission_expense',
 'Fee and commission expense', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_fee_commission_income', 'canonical', 'fee_commission_income',
 'Fee and commission income', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_finance_costs', 'canonical', 'finance_costs',
 'Finance costs', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_finance_income', 'canonical', 'finance_income',
 'Finance income', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_fx_effect_on_cash', 'canonical', 'fx_effect_on_cash',
 'FX effect on cash', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_fx_translation_reserve', 'canonical', 'fx_translation_reserve',
 'FX translation reserve', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_goodwill', 'canonical', 'goodwill',
 'Goodwill', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_ifrs9_impairment_loss_gain', 'canonical', 'ifrs9_impairment_loss_gain',
 'IFRS 9 impairment loss/gain', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_income_tax_expense', 'canonical', 'income_tax_expense',
 'Income tax expense', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_income_tax_oci_remeasurement_defined_benefit_plans', 'canonical', 'income_tax_oci_remeasurement_defined_benefit_plans',
 'Income tax on OCI — defined benefit plan remeasurements', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_income_taxes_paid_refund_operating', 'canonical', 'income_taxes_paid_refund_operating',
 'Income taxes paid/refunded (operating activities)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_intangible_assets_and_goodwill', 'canonical', 'intangible_assets_and_goodwill',
 'Intangible assets and goodwill', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_interest_paid_financing_activities', 'canonical', 'interest_paid_financing_activities',
 'Interest paid (financing activities)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_interest_received_investing', 'canonical', 'interest_received_investing',
 'Interest received (investing activities)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_interest_revenue_effective_interest_method', 'canonical', 'interest_revenue_effective_interest_method',
 'Interest revenue (effective interest method)', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_investing_cash_inflows', 'canonical', 'investing_cash_inflows',
 'Investing cash inflows', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_investing_cash_outflows', 'canonical', 'investing_cash_outflows',
 'Investing cash outflows', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_lease_liability_payments_financing', 'canonical', 'lease_liability_payments_financing',
 'Lease liability payments (financing activities)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_net_change_in_cash_before_fx', 'canonical', 'net_change_in_cash_before_fx',
 'Net change in cash before FX effect', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_net_profit_attributable_nci', 'canonical', 'net_profit_attributable_nci',
 'Net profit attributable to NCI', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_noncontrolling_interests', 'canonical', 'noncontrolling_interests',
 'Non-controlling interests', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_assets_held_for_sale', 'canonical', 'noncurrent_assets_held_for_sale',
 'Non-current assets held for sale', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_lease_liabilities', 'canonical', 'noncurrent_lease_liabilities',
 'Non-current lease liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_provisions_employee_benefits', 'canonical', 'noncurrent_provisions_employee_benefits',
 'Non-current provisions for employee benefits', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_oci_fx_translation_net_of_tax', 'canonical', 'oci_fx_translation_net_of_tax',
 'OCI — FX translation (net of tax)', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_oci_non_reclassifiable_net_of_tax', 'canonical', 'oci_non_reclassifiable_net_of_tax',
 'OCI not reclassifiable to profit or loss (net of tax)', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_oci_reclassifiable_net_of_tax', 'canonical', 'oci_reclassifiable_net_of_tax',
 'OCI reclassifiable to profit or loss (net of tax)', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_oci_remeasurement_defined_benefit_plans_before_tax', 'canonical', 'oci_remeasurement_defined_benefit_plans_before_tax',
 'OCI — defined benefit plan remeasurements (before tax)', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_other_adjustments_investing_or_financing_cash_effects', 'canonical', 'other_adjustments_investing_or_financing_cash_effects',
 'Other adjustments — investing/financing cash effects', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_other_adjustments_to_reconcile_profit_loss', 'canonical', 'other_adjustments_to_reconcile_profit_loss',
 'Other adjustments to reconcile profit/loss', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_other_comprehensive_income', 'canonical', 'other_comprehensive_income',
 'Other comprehensive income', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_other_current_financial_assets', 'canonical', 'other_current_financial_assets',
 'Other current financial assets', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_current_nonfinancial_assets', 'canonical', 'other_current_nonfinancial_assets',
 'Other current non-financial assets', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_expense_by_function', 'canonical', 'other_expense_by_function',
 'Other expense by function', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_other_income', 'canonical', 'other_income',
 'Other income', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_other_noncurrent_financial_assets', 'canonical', 'other_noncurrent_financial_assets',
 'Other non-current financial assets', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_reserves', 'canonical', 'other_reserves',
 'Other reserves', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_shortterm_provisions', 'canonical', 'other_shortterm_provisions',
 'Other short-term provisions', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_payments_to_acquire_or_redeem_own_shares', 'canonical', 'payments_to_acquire_or_redeem_own_shares',
 'Payments to acquire/redeem own shares', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_proceeds_from_borrowings_financing', 'canonical', 'proceeds_from_borrowings_financing',
 'Proceeds from borrowings (financing activities)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_proceeds_from_disposal_of_ppe_and_intangibles', 'canonical', 'proceeds_from_disposal_of_ppe_and_intangibles',
 'Proceeds from disposal of PP&E and intangibles', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_proceeds_from_issue_of_bonds', 'canonical', 'proceeds_from_issue_of_bonds',
 'Proceeds from issue of bonds, notes and debentures', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_property_plant_equipment', 'canonical', 'property_plant_equipment',
 'Property, plant and equipment', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_property_plant_equipment_incl_rou', 'canonical', 'property_plant_equipment_incl_rou',
 'Property, plant and equipment (incl. right-of-use)', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_provisions', 'canonical', 'provisions',
 'Provisions', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_purchase_of_treasury_shares', 'canonical', 'purchase_of_treasury_shares',
 'Purchase of treasury shares', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_repayments_of_bonds', 'canonical', 'repayments_of_bonds',
 'Repayments of bonds, notes and debentures', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_repayments_of_borrowings_financing', 'canonical', 'repayments_of_borrowings_financing',
 'Repayments of borrowings (financing activities)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_retained_earnings_appropriation', 'canonical', 'retained_earnings_appropriation',
 'Retained earnings appropriation', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_retained_earnings_current_period_profit', 'canonical', 'retained_earnings_current_period_profit',
 'Retained earnings — current period profit', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_retained_earnings_excl_current_period', 'canonical', 'retained_earnings_excl_current_period',
 'Retained earnings (excl. current period)', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_right_of_use_assets', 'canonical', 'right_of_use_assets',
 'Right-of-use assets', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_share_premium', 'canonical', 'share_premium',
 'Share premium', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_total_comprehensive_income', 'canonical', 'total_comprehensive_income',
 'Total comprehensive income', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_total_equity_and_liabilities', 'canonical', 'total_equity_and_liabilities',
 'Total equity and liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_treasury_shares', 'canonical', 'treasury_shares',
 'Treasury shares', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_weighted_average_shares', 'canonical', 'weighted_average_shares',
 'Weighted average shares', 'count', NULL, 'reported', NULL, 'seed', 'other', 'duration');
