-- ADR 0100 decision 2 / epic #398: the second crosswalk seed, from the
-- CORPUS-wide concept harvest rather than an 8-filing sample.
--
-- `storage::tests::real_data_extraction::corpus_concept_harvest_report` walks
-- every stored report package on the owner's disk (84 instance-bearing
-- documents), computes the Layer 1 generation the pipeline would produce, and
-- ranks uncrosswalked concepts by how many DISTINCT issuers tag them. This
-- seeds the 202 keys the crosswalk gained from that harvest's >=3-issuer
-- tier -- the threshold that separates a shared reporting vocabulary from one
-- company's habit.
--
-- Only STANDARD taxonomy concepts are here. An issuer extension carries the
-- company's own namespace, so it may never take a global canonical key (it
-- would assert a cross-company equivalence nobody proved); eleven such
-- concepts in the same tier are deliberately left uncurated, including four
-- that merely LOOK standard because several Polish filers share one vendor
-- taxonomy.
--
-- Reuse before mint still applies: a concept whose figure an existing key
-- already names resolves onto that key in the crosswalk and inserts nothing
-- here (net_profit_discontinued, noncurrent_assets_held_for_sale).
--
-- origin/statement_group/period_nature are set explicitly AT INSERT (the
-- 0129/0130/0141 convention). `period_nature` is the harvest's MEASURED value,
-- never a guess from the concept name. INSERT OR IGNORE on stable bare
-- canonical ids so a re-run, or a key that later gains a curated override, is
-- never clobbered.

-- Self-healing preamble (sol review finding 10): `INSERT OR IGNORE` is the
-- exact mechanism migration 0125 documents as silently suppressing a
-- canonical seed when a malformed non-canonical row squats on the bare
-- `kpidef_<key>` id (possible again only via an import of pre-0125 data).
-- Re-key any such row first — 0125's own statements, verbatim semantics —
-- so no seed below can vanish without error. A clean database matches
-- nothing and this is a no-op.
PRAGMA defer_foreign_keys = ON;

CREATE TEMP TABLE _m0148_rekey AS
SELECT
    d.id AS old_id,
    d.id || '__'
        || CASE d.scope WHEN 'company' THEN 'c' WHEN 'sector' THEN 's' ELSE d.scope END
        || '_'
        || CASE d.scope
               WHEN 'company' THEN IFNULL(d.company_id, '')
               WHEN 'sector' THEN IFNULL(d.sector, '')
               ELSE IFNULL(d.company_id, IFNULL(d.sector, ''))
           END AS new_id
FROM kpi_definitions d
WHERE d.scope <> 'canonical'
  AND d.id = 'kpidef_' || LOWER(d.metric_key);

UPDATE kpi_definitions
SET id = (SELECT r.new_id FROM _m0148_rekey r WHERE r.old_id = id),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id IN (SELECT old_id FROM _m0148_rekey);

UPDATE kpi_relevance
SET definition_id = (
        SELECT r.new_id FROM _m0148_rekey r WHERE r.old_id = definition_id
    )
WHERE definition_id IN (SELECT old_id FROM _m0148_rekey);

UPDATE financial_facts
SET definition_id = (
        SELECT r.new_id FROM _m0148_rekey r WHERE r.old_id = definition_id
    )
WHERE definition_id IN (SELECT old_id FROM _m0148_rekey);

DROP TABLE _m0148_rekey;

INSERT OR IGNORE INTO kpi_definitions
    (id, scope, metric_key, label, value_kind, unit, computation, formula, origin, statement_group, period_nature) VALUES
('kpidef_accruals_classified_as_current', 'canonical', 'accruals_classified_as_current',
 'Accruals classified as current', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_adj_amortisation_expense', 'canonical', 'adj_amortisation_expense',
 'Adjustment — amortisation expense', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_change_in_accrued_income_excl_contract_assets', 'canonical', 'adj_change_in_accrued_income_excl_contract_assets',
 'Adjustment — change in accrued income excluding contract assets', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_change_in_contract_assets', 'canonical', 'adj_change_in_contract_assets',
 'Adjustment — change in contract assets', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_change_in_contract_liabilities', 'canonical', 'adj_change_in_contract_liabilities',
 'Adjustment — change in contract liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_change_in_deferred_income_excl_contract_liabilities', 'canonical', 'adj_change_in_deferred_income_excl_contract_liabilities',
 'Adjustment — change in deferred income excluding contract liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_change_in_deferred_income_including_contract_liabilities', 'canonical', 'adj_change_in_deferred_income_including_contract_liabilities',
 'Adjustment — change in deferred income including contract liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_change_in_deposits_from_customers', 'canonical', 'adj_change_in_deposits_from_customers',
 'Adjustment — change in deposits from customers', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_change_in_employee_benefit_liabilities', 'canonical', 'adj_change_in_employee_benefit_liabilities',
 'Adjustment — change in employee benefit liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_change_in_other_assets', 'canonical', 'adj_change_in_other_assets',
 'Adjustment — change in other assets', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_change_in_other_liabilities', 'canonical', 'adj_change_in_other_liabilities',
 'Adjustment — change in other liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_change_in_prepaid_expenses', 'canonical', 'adj_change_in_prepaid_expenses',
 'Adjustment — change in prepaid expenses', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_change_in_trade_account_payable', 'canonical', 'adj_change_in_trade_account_payable',
 'Adjustment — change in trade account payable', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_change_in_trade_account_receivable', 'canonical', 'adj_change_in_trade_account_receivable',
 'Adjustment — change in trade account receivable', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_depreciation_expense', 'canonical', 'adj_depreciation_expense',
 'Adjustment — depreciation expense', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_dividend_income', 'canonical', 'adj_dividend_income',
 'Adjustment — dividend income', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_fair_value_gains_losses', 'canonical', 'adj_fair_value_gains_losses',
 'Adjustment — fair value gains losses', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_finance_costs', 'canonical', 'adj_finance_costs',
 'Adjustment — finance costs', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_finance_income_cost', 'canonical', 'adj_finance_income_cost',
 'Adjustment — finance income cost', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_disposal_gains_subsidiaries_joint_ventures_associates', 'canonical', 'adj_disposal_gains_subsidiaries_joint_ventures_associates',
 'Adjustment — gain loss on disposal of investments in subsidiaries joint ventures and associates', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_gains_losses_on_change_in_fair_value_of_derivatives', 'canonical', 'adj_gains_losses_on_change_in_fair_value_of_derivatives',
 'Adjustment — gains losses on change in fair value of derivatives', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_goodwill_impairment_in_profit_or_loss', 'canonical', 'adj_goodwill_impairment_in_profit_or_loss',
 'Adjustment — impairment loss recognised in profit or loss goodwill', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_impairment_loss_reversal_in_profit_or_loss', 'canonical', 'adj_impairment_loss_reversal_in_profit_or_loss',
 'Adjustment — impairment loss reversal of impairment loss recognised in profit or loss', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_interest_expense', 'canonical', 'adj_interest_expense',
 'Adjustment — interest expense', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_interest_income', 'canonical', 'adj_interest_income',
 'Adjustment — interest income', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_provisions', 'canonical', 'adj_provisions',
 'Adjustment — provisions', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_sharebased_payments', 'canonical', 'adj_sharebased_payments',
 'Adjustment — sharebased payments', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_undistributed_profits_of_associates', 'canonical', 'adj_undistributed_profits_of_associates',
 'Adjustment — undistributed profits of associates', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adj_undistributed_profits_of_equity_method_investments', 'canonical', 'adj_undistributed_profits_of_equity_method_investments',
 'Adjustment — undistributed profits of investments (equity method)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_adjusted_weighted_average_shares', 'canonical', 'adjusted_weighted_average_shares',
 'Adjusted weighted average shares', 'count', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_adj_to_reconcile_profit_loss_excl_working_capital', 'canonical', 'adj_to_reconcile_profit_loss_excl_working_capital',
 'Adjustments to reconcile profit loss excluding changes in working capital', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_basic_earnings_loss_per_share_from_discontinued_operations', 'canonical', 'basic_earnings_loss_per_share_from_discontinued_operations',
 'Basic earnings loss per share from discontinued operations', 'monetary', NULL, 'reported', NULL, 'seed', 'per_share', 'duration'),
('kpidef_capital_redemption_reserve', 'canonical', 'capital_redemption_reserve',
 'Capital redemption reserve', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_capital_reserve', 'canonical', 'capital_reserve',
 'Capital reserve', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_cash_advances_and_loans_made_to_other_parties_investing', 'canonical', 'cash_advances_and_loans_made_to_other_parties_investing',
 'Cash advances and loans made to other parties (investing)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_cash_advances_and_loans_made_to_related_parties', 'canonical', 'cash_advances_and_loans_made_to_related_parties',
 'Cash advances and loans made to related parties', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_cash_flows_from_losing_control_of_subsidiaries_investing', 'canonical', 'cash_flows_from_losing_control_of_subsidiaries_investing',
 'Cash flows from losing control of subsidiaries or other businesses (investing)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_change_in_short_term_deposits_and_investments_cash_flows', 'canonical', 'change_in_short_term_deposits_and_investments_cash_flows',
 'Cash flows from decrease increase in shortterm deposits and investments', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_cash_flows_from_operations_before_working_capital_changes', 'canonical', 'cash_flows_from_operations_before_working_capital_changes',
 'Cash flows from operations before changes in working capital', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_repayments_received_of_loans_made_to_related_parties', 'canonical', 'repayments_received_of_loans_made_to_related_parties',
 'Cash receipts from repayment of advances and loans made to related parties', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_repayments_received_of_loans_made_to_other_parties', 'canonical', 'repayments_received_of_loans_made_to_other_parties',
 'Cash receipts from repayment of advances and loans made to other parties (investing)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_change_in_working_capital', 'canonical', 'change_in_working_capital',
 'Increase decrease in working capital', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_change_through_acquisition_of_subsidiary', 'canonical', 'change_through_acquisition_of_subsidiary',
 'Equity change — acquisition of subsidiary', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_change_through_change_in_equity_of_subsidiaries', 'canonical', 'change_through_change_in_equity_of_subsidiaries',
 'Equity change — change in equity of subsidiaries', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_change_through_disposal_of_subsidiary', 'canonical', 'change_through_disposal_of_subsidiary',
 'Equity change — disposal of subsidiary', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_change_through_transactions_with_owners', 'canonical', 'change_through_transactions_with_owners',
 'Equity change — transactions with owners', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_change_through_transfer_to_statutory_reserve', 'canonical', 'change_through_transfer_to_statutory_reserve',
 'Equity change — transfer to statutory reserve', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_change_through_treasury_share_transactions', 'canonical', 'change_through_treasury_share_transactions',
 'Equity change — treasury share transactions', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_changes_in_equity', 'canonical', 'changes_in_equity',
 'Changes in equity', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_changes_in_inventories_of_finished_goods_and_work_in_progress', 'canonical', 'changes_in_inventories_of_finished_goods_and_work_in_progress',
 'Changes in inventories of finished goods and work in progress', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_cost_of_merchandise_sold', 'canonical', 'cost_of_merchandise_sold',
 'Cost of merchandise sold', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_current_assets_excl_held_for_sale_or_distribution', 'canonical', 'current_assets_excl_held_for_sale_or_distribution',
 'Current assets excluding assets or disposal groups classified as held for sale or as held for distribution to owners', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_bonds_issued_and_current_portion_of_bonds_issued', 'canonical', 'current_bonds_issued_and_current_portion_of_bonds_issued',
 'Current bonds issued and current portion of noncurrent bonds issued', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_borrowings_and_current_portion_of_borrowings', 'canonical', 'current_borrowings_and_current_portion_of_borrowings',
 'Current borrowings and current portion of noncurrent borrowings', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_contract_assets', 'canonical', 'current_contract_assets',
 'Current contract assets', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_contract_liabilities', 'canonical', 'current_contract_liabilities',
 'Current contract liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_deferred_income_including_current_contract_liabilities', 'canonical', 'current_deferred_income_including_current_contract_liabilities',
 'Current deferred income including current contract liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_derivative_financial_assets', 'canonical', 'current_derivative_financial_assets',
 'Current derivative financial assets', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_derivative_financial_liabilities', 'canonical', 'current_derivative_financial_liabilities',
 'Current derivative financial liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_finance_lease_receivables', 'canonical', 'current_finance_lease_receivables',
 'Current finance lease receivables', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_financial_assets_at_amortised_cost', 'canonical', 'current_financial_assets_at_amortised_cost',
 'Current financial assets at amortised cost', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_government_grants', 'canonical', 'current_government_grants',
 'Current government grants', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_liabilities_excl_liabilities_held_for_sale', 'canonical', 'current_liabilities_excl_liabilities_held_for_sale',
 'Current liabilities excluding liabilities included in disposal groups classified as held for sale', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_loans_received_and_current_portion_of_loans_received', 'canonical', 'current_loans_received_and_current_portion_of_loans_received',
 'Current loans received and current portion of noncurrent loans received', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_payables_on_social_security_and_taxes_excl_income_tax', 'canonical', 'current_payables_on_social_security_and_taxes_excl_income_tax',
 'Current payables on social security and taxes excluding income tax', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_prepaid_expenses', 'canonical', 'current_prepaid_expenses',
 'Current prepaid expenses', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_prepayments', 'canonical', 'current_prepayments',
 'Current prepayments', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_prepayments_and_accrued_income_excl_contract_assets', 'canonical', 'current_prepayments_and_accrued_income_excl_contract_assets',
 'Current prepayments and current accrued income excluding current contract assets', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_provisions', 'canonical', 'current_provisions',
 'Current provisions', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_receivables_from_taxes_excl_income_tax', 'canonical', 'current_receivables_from_taxes_excl_income_tax',
 'Current receivables from taxes excluding income tax', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_restricted_cash', 'canonical', 'current_restricted_cash',
 'Current restricted cash and cash equivalents', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_current_secured_bank_loans_and_current_portion_of_noncurrent', 'canonical', 'current_secured_bank_loans_and_current_portion_of_noncurrent',
 'Current secured bank loans received and current portion of noncurrent secured bank loans received', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_depreciation_amortisation', 'canonical', 'depreciation_amortisation',
 'Depreciation and amortisation expense', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_derivative_financial_liabilities', 'canonical', 'derivative_financial_liabilities',
 'Derivative financial liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_diluted_earnings_loss_per_share_from_discontinued_operations', 'canonical', 'diluted_earnings_loss_per_share_from_discontinued_operations',
 'Diluted earnings loss per share from discontinued operations', 'monetary', NULL, 'reported', NULL, 'seed', 'per_share', 'duration'),
('kpidef_distribution_costs', 'canonical', 'distribution_costs',
 'Distribution costs', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_dividends_paid_to_nci_financing', 'canonical', 'dividends_paid_to_nci_financing',
 'Dividends paid to NCI (financing)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_dividends_proposed_not_recognised', 'canonical', 'dividends_proposed_not_recognised',
 'Dividends proposed or declared before financial statements authorised for issue but not recognised as distribution to owners', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_dividends_proposed_not_recognised_per_share', 'canonical', 'dividends_proposed_not_recognised_per_share',
 'Dividends proposed or declared before financial statements authorised for issue but not recognised as distribution to owners per share', 'monetary', NULL, 'reported', NULL, 'seed', 'per_share', 'duration'),
('kpidef_dividends_received_investing', 'canonical', 'dividends_received_investing',
 'Dividends received (investing)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_dividends_recognised_as_distributions_to_nci', 'canonical', 'dividends_recognised_as_distributions_to_nci',
 'Dividends recognised as distributions to NCI', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_dividends_recognised_as_distributions_to_owners_of_parent', 'canonical', 'dividends_recognised_as_distributions_to_owners_of_parent',
 'Dividends recognised as distributions to owners of parent', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_employee_benefits_expense', 'canonical', 'employee_benefits_expense',
 'Employee benefits expense', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_expense_by_nature', 'canonical', 'expense_by_nature',
 'Expense by nature', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_finance_income_cost', 'canonical', 'finance_income_cost',
 'Finance income cost', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_gain_recognised_in_bargain_purchase_transaction', 'canonical', 'gain_recognised_in_bargain_purchase_transaction',
 'Gain recognised in bargain purchase transaction', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_gains_losses_on_cash_flow_hedges_before_tax', 'canonical', 'gains_losses_on_cash_flow_hedges_before_tax',
 'Gains losses on cash flow hedges before tax', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_fx_translation_gains_losses_in_profit_or_loss', 'canonical', 'fx_translation_gains_losses_in_profit_or_loss',
 'Gains losses on exchange differences on translation recognised in profit or loss', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_gains_losses_on_exchange_differences_on_translation_net_of_tax', 'canonical', 'gains_losses_on_exchange_differences_on_translation_net_of_tax',
 'Gains losses on exchange differences on translation net of tax', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_gains_losses_on_net_monetary_position', 'canonical', 'gains_losses_on_net_monetary_position',
 'Gains losses on net monetary position', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_general_and_administrative_expense', 'canonical', 'general_and_administrative_expense',
 'General and administrative expense', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_impairment_loss_reversal_in_profit_or_loss', 'canonical', 'impairment_loss_reversal_in_profit_or_loss',
 'Impairment loss reversal of impairment loss recognised in profit or loss', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_income_tax_relating_to_cash_flow_hedges_of_oci', 'canonical', 'income_tax_relating_to_cash_flow_hedges_of_oci',
 'Income tax relating to cash flow hedges of OCI', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_income_tax_relating_to_components_of_oci_non_reclassifiable', 'canonical', 'income_tax_relating_to_components_of_oci_non_reclassifiable',
 'Income tax relating to components of OCI (non-reclassifiable)', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_income_tax_relating_to_components_of_oci_reclassifiable', 'canonical', 'income_tax_relating_to_components_of_oci_reclassifiable',
 'Income tax relating to components of OCI (reclassifiable)', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_income_taxes_paid_operating', 'canonical', 'income_taxes_paid_operating',
 'Income taxes paid (operating)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_intangible_assets_excl_goodwill', 'canonical', 'intangible_assets_excl_goodwill',
 'Intangible assets excluding goodwill', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_interest_paid_operating', 'canonical', 'interest_paid_operating',
 'Interest paid (operating)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_interest_received_operating', 'canonical', 'interest_received_operating',
 'Interest received (operating)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_investment_equity_method', 'canonical', 'investment_equity_method',
 'Investment (equity method)', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_investment_property', 'canonical', 'investment_property',
 'Investment property', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_investments_in_associates_equity_method', 'canonical', 'investments_in_associates_equity_method',
 'Investments in associates (equity method)', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_investments_in_joint_ventures_equity_method', 'canonical', 'investments_in_joint_ventures_equity_method',
 'Investments in joint ventures (equity method)', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_investments_in_subsidiaries_joint_ventures_associates', 'canonical', 'investments_in_subsidiaries_joint_ventures_associates',
 'Investments in subsidiaries joint ventures and associates', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_issue_of_equity', 'canonical', 'issue_of_equity',
 'Issue of equity', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_liabilities_held_for_sale', 'canonical', 'liabilities_held_for_sale',
 'Liabilities included in disposal groups classified as held for sale', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_miscellaneous_other_operating_expense', 'canonical', 'miscellaneous_other_operating_expense',
 'Miscellaneous other operating expense', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_miscellaneous_other_operating_income', 'canonical', 'miscellaneous_other_operating_income',
 'Miscellaneous other operating income', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_net_deferred_tax_assets', 'canonical', 'net_deferred_tax_assets',
 'Net deferred tax assets', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_net_deferred_tax_liabilities', 'canonical', 'net_deferred_tax_liabilities',
 'Net deferred tax liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_net_profit_continuing', 'canonical', 'net_profit_continuing',
 'Profit loss from continuing operations', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_noncurrent_assets_held_for_sale_or_distribution', 'canonical', 'noncurrent_assets_held_for_sale_or_distribution',
 'Non-current assets held for sale or for distribution to owners', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_accruals_and_deferred_income_incl_contracts', 'canonical', 'noncurrent_accruals_and_deferred_income_incl_contracts',
 'Noncurrent accruals and noncurrent deferred income including noncurrent contract liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_accrued_income_excl_noncurrent_contract_assets', 'canonical', 'noncurrent_accrued_income_excl_noncurrent_contract_assets',
 'Noncurrent accrued income excluding noncurrent contract assets', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_contract_liabilities', 'canonical', 'noncurrent_contract_liabilities',
 'Noncurrent contract liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_deferred_income_excl_noncurrent_contract_liabilities', 'canonical', 'noncurrent_deferred_income_excl_noncurrent_contract_liabilities',
 'Noncurrent deferred income excluding noncurrent contract liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_derivative_financial_assets', 'canonical', 'noncurrent_derivative_financial_assets',
 'Noncurrent derivative financial assets', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_derivative_financial_liabilities', 'canonical', 'noncurrent_derivative_financial_liabilities',
 'Noncurrent derivative financial liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_finance_lease_receivables', 'canonical', 'noncurrent_finance_lease_receivables',
 'Noncurrent finance lease receivables', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_financial_assets_at_amortised_cost', 'canonical', 'noncurrent_financial_assets_at_amortised_cost',
 'Noncurrent financial assets at amortised cost', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_government_grants', 'canonical', 'noncurrent_government_grants',
 'Noncurrent government grants', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_payables', 'canonical', 'noncurrent_payables',
 'Noncurrent payables', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_portion_of_loans_received', 'canonical', 'noncurrent_portion_of_loans_received',
 'Noncurrent portion of noncurrent loans received', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_portion_of_secured_bank_loans_received', 'canonical', 'noncurrent_portion_of_secured_bank_loans_received',
 'Noncurrent portion of noncurrent secured bank loans received', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_prepayments', 'canonical', 'noncurrent_prepayments',
 'Noncurrent prepayments', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_prepayments_accrued_income_excl_contract_assets', 'canonical', 'noncurrent_prepayments_accrued_income_excl_contract_assets',
 'Noncurrent prepayments and noncurrent accrued income excluding noncurrent contract assets', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_provisions', 'canonical', 'noncurrent_provisions',
 'Noncurrent provisions', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_noncurrent_receivables', 'canonical', 'noncurrent_receivables',
 'Noncurrent receivables', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_oci_before_tax', 'canonical', 'oci_before_tax',
 'OCI before tax', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_oci_before_tax_cash_flow_hedges', 'canonical', 'oci_before_tax_cash_flow_hedges',
 'OCI before tax cash flow hedges', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_oci_before_tax_exchange_differences_on_translation', 'canonical', 'oci_before_tax_exchange_differences_on_translation',
 'OCI before tax exchange differences on translation', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_oci_before_tax_gains_losses_equity_investments', 'canonical', 'oci_before_tax_gains_losses_equity_investments',
 'OCI before tax gains losses from investments in equity instruments', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_oci_net_of_tax_cash_flow_hedges', 'canonical', 'oci_net_of_tax_cash_flow_hedges',
 'OCI net of tax cash flow hedges', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_oci_net_of_tax_gains_losses_defined_benefit_remeasurement', 'canonical', 'oci_net_of_tax_gains_losses_defined_benefit_remeasurement',
 'OCI net of tax gains losses on remeasurements of defined benefit plans', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_oci_net_of_tax_gains_losses_equity_investments', 'canonical', 'oci_net_of_tax_gains_losses_equity_investments',
 'OCI net of tax gains losses from investments in equity instruments', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_oci_net_of_tax_gains_losses_on_revaluation', 'canonical', 'oci_net_of_tax_gains_losses_on_revaluation',
 'OCI net of tax gains losses on revaluation', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_oci_non_reclassifiable_before_tax', 'canonical', 'oci_non_reclassifiable_before_tax',
 'OCI (non-reclassifiable) before tax', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_oci_reclassifiable_before_tax', 'canonical', 'oci_reclassifiable_before_tax',
 'OCI (reclassifiable) before tax', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_operating_expense', 'canonical', 'operating_expense',
 'Operating expense', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_other_adj_noncash_items', 'canonical', 'other_adj_noncash_items',
 'Adjustment — other non-cash items', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_other_assets', 'canonical', 'other_assets',
 'Other assets', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_cash_payments_to_acquire_other_entity_securities_investing', 'canonical', 'other_cash_payments_to_acquire_other_entity_securities_investing',
 'Other cash payments to acquire equity or debt instruments of other entities (investing)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_other_cash_receipts_from_sales_of_other_entity_securities', 'canonical', 'other_cash_receipts_from_sales_of_other_entity_securities',
 'Other cash receipts from sales of equity or debt instruments of other entities (investing)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_other_current_assets', 'canonical', 'other_current_assets',
 'Other current assets', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_current_financial_liabilities', 'canonical', 'other_current_financial_liabilities',
 'Other current financial liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_current_liabilities', 'canonical', 'other_current_liabilities',
 'Other current liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_current_nonfinancial_liabilities', 'canonical', 'other_current_nonfinancial_liabilities',
 'Other current nonfinancial liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_current_payables', 'canonical', 'other_current_payables',
 'Other current payables', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_current_receivables', 'canonical', 'other_current_receivables',
 'Other current receivables', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_equity_interest', 'canonical', 'other_equity_interest',
 'Other equity interest', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_expense_by_nature', 'canonical', 'other_expense_by_nature',
 'Other expense by nature', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_other_finance_income_cost', 'canonical', 'other_finance_income_cost',
 'Other finance income cost', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_other_inflows_outflows_of_cash_financing', 'canonical', 'other_inflows_outflows_of_cash_financing',
 'Other inflows outflows of cash (financing)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_other_inflows_outflows_of_cash_investing', 'canonical', 'other_inflows_outflows_of_cash_investing',
 'Other inflows outflows of cash (investing)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_other_inflows_outflows_of_cash_operating', 'canonical', 'other_inflows_outflows_of_cash_operating',
 'Other inflows outflows of cash (operating)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_other_long_term_provisions', 'canonical', 'other_long_term_provisions',
 'Other longterm provisions', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_noncurrent_assets', 'canonical', 'other_noncurrent_assets',
 'Other noncurrent assets', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_noncurrent_financial_liabilities', 'canonical', 'other_noncurrent_financial_liabilities',
 'Other noncurrent financial liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_noncurrent_liabilities', 'canonical', 'other_noncurrent_liabilities',
 'Other noncurrent liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_noncurrent_nonfinancial_assets', 'canonical', 'other_noncurrent_nonfinancial_assets',
 'Other noncurrent nonfinancial assets', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_noncurrent_nonfinancial_liabilities', 'canonical', 'other_noncurrent_nonfinancial_liabilities',
 'Other noncurrent nonfinancial liabilities', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_noncurrent_payables', 'canonical', 'other_noncurrent_payables',
 'Other noncurrent payables', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_noncurrent_receivables', 'canonical', 'other_noncurrent_receivables',
 'Other noncurrent receivables', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_other_receivables', 'canonical', 'other_receivables',
 'Other receivables', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_payments_from_ownership_changes_in_subsidiaries', 'canonical', 'payments_from_ownership_changes_in_subsidiaries',
 'Payments from changes in ownership interests in subsidiaries', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_proceeds_from_contributions_of_nci', 'canonical', 'proceeds_from_contributions_of_nci',
 'Proceeds from contributions of NCI', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_proceeds_from_government_grants_financing', 'canonical', 'proceeds_from_government_grants_financing',
 'Proceeds from government grants (financing)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_proceeds_from_government_grants_investing', 'canonical', 'proceeds_from_government_grants_investing',
 'Proceeds from government grants (investing)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_proceeds_from_issuing_shares', 'canonical', 'proceeds_from_issuing_shares',
 'Proceeds from issuing shares', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_proceeds_from_ownership_changes_in_subsidiaries', 'canonical', 'proceeds_from_ownership_changes_in_subsidiaries',
 'Proceeds from changes in ownership interests in subsidiaries', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_proceeds_from_sales_of_intangible_assets_investing', 'canonical', 'proceeds_from_sales_of_intangible_assets_investing',
 'Proceeds from sales of intangible assets (investing)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_proceeds_from_sales_of_interests_in_associates', 'canonical', 'proceeds_from_sales_of_interests_in_associates',
 'Proceeds from sales of interests in associates', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_proceeds_from_sales_of_investment_property', 'canonical', 'proceeds_from_sales_of_investment_property',
 'Proceeds from sales of investment property', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_proceeds_from_sales_of_ppe_investing', 'canonical', 'proceeds_from_sales_of_ppe_investing',
 'Proceeds from sales of PP&E (investing)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_proceeds_from_sales_or_maturity_of_financial_instruments', 'canonical', 'proceeds_from_sales_or_maturity_of_financial_instruments',
 'Proceeds from sales or maturity of financial instruments (investing)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_purchase_of_financial_instruments_investing', 'canonical', 'purchase_of_financial_instruments_investing',
 'Purchase of financial instruments (investing)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_purchase_of_intangible_assets_investing', 'canonical', 'purchase_of_intangible_assets_investing',
 'Purchase of intangible assets (investing)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_purchase_of_interests_in_equity_method_investments', 'canonical', 'purchase_of_interests_in_equity_method_investments',
 'Purchase of interests in investments (equity method)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_purchase_of_investment_property', 'canonical', 'purchase_of_investment_property',
 'Purchase of investment property', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_purchase_of_ppe_investing', 'canonical', 'purchase_of_ppe_investing',
 'Purchase of PP&E (investing)', 'monetary', NULL, 'reported', NULL, 'seed', 'cash_flow', 'duration'),
('kpidef_raw_materials_and_consumables_used', 'canonical', 'raw_materials_and_consumables_used',
 'Raw materials and consumables used', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_research_and_development_expense', 'canonical', 'research_and_development_expense',
 'Research and development expense', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_reserve_defined_benefit_remeasurement', 'canonical', 'reserve_defined_benefit_remeasurement',
 'Reserve of remeasurements of defined benefit plans', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_reserve_of_cash_flow_hedges', 'canonical', 'reserve_of_cash_flow_hedges',
 'Reserve of cash flow hedges', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_reserve_of_sharebased_payments', 'canonical', 'reserve_of_sharebased_payments',
 'Reserve of sharebased payments', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_restricted_cash', 'canonical', 'restricted_cash',
 'Restricted cash and cash equivalents', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_revenue_from_rendering_of_services', 'canonical', 'revenue_from_rendering_of_services',
 'Revenue from rendering of services', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_revenue_from_sale_of_goods', 'canonical', 'revenue_from_sale_of_goods',
 'Revenue from sale of goods', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_right_of_use_assets_not_investment_property', 'canonical', 'right_of_use_assets_not_investment_property',
 'Rightofuse assets that do not meet definition of investment property', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_sale_or_issue_of_treasury_shares', 'canonical', 'sale_or_issue_of_treasury_shares',
 'Sale or issue of treasury shares', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_sales_and_marketing_expense', 'canonical', 'sales_and_marketing_expense',
 'Sales and marketing expense', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_selling_expense', 'canonical', 'selling_expense',
 'Selling expense', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_services_expense', 'canonical', 'services_expense',
 'Services expense', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_share_of_oci_of_associates_jvs_reclassifiable_net_of_tax', 'canonical', 'share_of_oci_of_associates_jvs_reclassifiable_net_of_tax',
 'Share of OCI of associates and joint ventures (equity method) (reclassifiable) net of tax', 'monetary', NULL, 'reported', NULL, 'seed', 'other', 'duration'),
('kpidef_share_of_profit_loss_of_associates_and_jvs_equity_method', 'canonical', 'share_of_profit_loss_of_associates_and_jvs_equity_method',
 'Share of profit loss of associates and joint ventures (equity method)', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_share_of_profit_loss_of_joint_ventures_equity_method', 'canonical', 'share_of_profit_loss_of_joint_ventures_equity_method',
 'Share of profit loss of joint ventures (equity method)', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_short_term_borrowings', 'canonical', 'short_term_borrowings',
 'Shortterm borrowings', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_statutory_reserve', 'canonical', 'statutory_reserve',
 'Statutory reserve', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_tax_expense_excl_income_tax_expense', 'canonical', 'tax_expense_excl_income_tax_expense',
 'Tax expense excluding income tax expense', 'monetary', NULL, 'reported', NULL, 'seed', 'income', 'duration'),
('kpidef_trade_and_other_current_payables', 'canonical', 'trade_and_other_current_payables',
 'Trade and other current payables', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_trade_and_other_current_payables_to_trade_suppliers', 'canonical', 'trade_and_other_current_payables_to_trade_suppliers',
 'Trade and other current payables to trade suppliers', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_trade_and_other_current_receivables', 'canonical', 'trade_and_other_current_receivables',
 'Trade and other current receivables', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant'),
('kpidef_trade_and_other_payables_to_trade_suppliers', 'canonical', 'trade_and_other_payables_to_trade_suppliers',
 'Trade and other payables to trade suppliers', 'monetary', NULL, 'reported', NULL, 'seed', 'balance', 'instant');
