use super::companies::company_directories_are_stale;
use super::feed_matching::{media_duplicate_signature, MediaMatchCompany};
use super::migrations::{apply_migrations, database_status, expected_migration_count};
use super::ownership::normalize_holder_name;
use super::*;

const PORTAL_ANALIZ_ADAPTER_ID: &str = "portal-analiz";
use crate::source_adapters::gpw_company_registry::ADAPTER_ID as GPW_REGISTRY_ADAPTER_ID;
use crate::source_adapters::newconnect_company_directory::ADAPTER_ID as NEWCONNECT_DIRECTORY_ADAPTER_ID;

mod analyst_recommendations;
mod attention;
mod autopilot;
mod backup_pool;
mod cockpit_layouts;
mod common;
mod companies;
mod decision_journal;
mod diagnostics;
mod espi_cover_note_facts;
mod events;
mod feed_sources;
mod financials;
mod fundamentals_provenance;
mod import_export;
mod insider;
mod job_queue;
mod licensing;
mod management_claims;
mod management_holdings;
mod migration_safety;
mod mock_fidelity;
mod notebooks;
mod ownership;
mod quality_frameworks;
mod real_data_extraction;
mod real_data_health_coverage;
mod real_data_health_scores;
mod real_data_honesty;
mod real_data_insider;
mod real_data_management_holdings;
mod real_data_ownership;
mod real_data_shape_inventory;
mod real_data_t4_bank_insurance;
mod real_data_trust_audit;
mod red_flags;
mod report_documents;
mod report_expectations;
mod report_season;
mod research;
mod research_reminders;
mod schema;
mod search;
mod settings;
mod severity;
mod shape_corpus;
mod short_positions;
mod signals;
mod source_registry;
mod t7_cbf_corpus;
mod transcripts;
mod watchlists;
