use super::companies::company_directories_are_stale;
use super::feed_matching::{media_duplicate_signature, MediaMatchCompany};
use super::migrations::{apply_migrations, database_status, expected_migration_count};
use super::*;

const PORTAL_ANALIZ_ADAPTER_ID: &str = "portal-analiz";
use crate::source_adapters::gpw_company_registry::ADAPTER_ID as GPW_REGISTRY_ADAPTER_ID;
use crate::source_adapters::newconnect_company_directory::ADAPTER_ID as NEWCONNECT_DIRECTORY_ADAPTER_ID;

mod ai_analysis;
mod attention;
mod autopilot;
mod backup_pool;
mod cockpit_layouts;
mod common;
mod companies;
mod decision_journal;
mod diagnostics;
mod events;
mod extraction_metrics;
mod feed_sources;
mod financials;
mod import_export;
mod job_queue;
mod licensing;
mod management_claims;
mod migration_safety;
mod mock_fidelity;
mod notebooks;
mod ocr_extraction_profile;
mod quality_frameworks;
mod real_data_extraction;
mod report_documents;
mod report_expectations;
mod report_season;
mod research;
mod research_briefs;
mod research_reminders;
mod schema;
mod search;
mod settings;
mod signals;
mod source_registry;
mod t7_cbf_corpus;
mod transcripts;
mod watchlists;
