import type { FormEvent } from "react";
import type { AppLocale, CredentialStatus, FeedPruneResult, ShortcutBindingSetting, Theme, UserSettings } from "../../api/types";
import type { AppShortcutReferenceItem } from "../../app/shortcuts";

export type SettingsScreenProps = {
  theme: Theme;
  locale: AppLocale;
  settings: UserSettings | null;
  settingsError: string | null;
  feedPruneRetentionDays: number;
  feedPruneResult: FeedPruneResult | null;
  geminiCredentialStatus: CredentialStatus | null;
  geminiCredentialError: string | null;
  geminiCredentialInFlight: boolean;
  geminiApiKeyDraft: string;
  shortcutBindings: Record<string, ShortcutBindingSetting>;
  shortcutReferences: AppShortcutReferenceItem[];
  onThemeChange: (theme: Theme) => void;
  onLocaleChange: (locale: AppLocale) => void;
  onPollIntervalChange: (pollIntervalSeconds: number) => void;
  onShortcutBindingsChange: (shortcutBindings: Record<string, ShortcutBindingSetting>) => void;
  onYoutubeTranscriptionModelChange: (model: string) => void;
  onYoutubeTranscriptionTimeoutChange: (timeoutSeconds: number) => void;
  onGeminiApiKeyDraftChange: (apiKey: string) => void;
  onSaveGeminiApiKey: (event: FormEvent<HTMLFormElement>) => void;
  onClearGeminiApiKey: () => void;
  onOpenGeminiApiKeyPage: () => void;
  formatTimestamp: (value: string | null | undefined, emptyLabel?: string) => string;
  formatPollInterval: (seconds: number) => string;
  formatAiProvider: (value: string | null | undefined) => string;
  formatGeminiModel: (value: string | null | undefined) => string;
  formatCredentialConfigured: (status: CredentialStatus | null) => string;
  formatCredentialStorage: (value: string | null | undefined) => string;
  formatCredentialKind: (value: string | null | undefined) => string;
};
