import type { FormEvent } from "react";
import type { AccentPalette, AppLocale, CredentialStatus, FeedPruneResult, LicenseStatus, ShortcutBindingSetting, Theme, UserSettings } from "../../api/types";
import type { CapabilityProviderEntry } from "../../api/generated/CapabilityProviderEntry";
import type { AppShortcutReferenceItem } from "../../app/shortcuts";

export type SettingsScreenProps = {
  theme: Theme;
  accentPalette: AccentPalette;
  locale: AppLocale;
  settings: UserSettings | null;
  settingsError: string | null;
  licenseStatus: LicenseStatus | null;
  licenseError: string | null;
  licenseInFlight: boolean;
  licenseKeyDraft: string;
  feedPruneRetentionDays: number;
  feedPruneResult: FeedPruneResult | null;
  geminiCredentialStatus: CredentialStatus | null;
  geminiCredentialError: string | null;
  geminiCredentialInFlight: boolean;
  geminiApiKeyDraft: string;
  shortcutBindings: Record<string, ShortcutBindingSetting>;
  shortcutReferences: AppShortcutReferenceItem[];
  onThemeChange: (theme: Theme) => void;
  onAccentPaletteChange: (accentPalette: AccentPalette) => void;
  onLocaleChange: (locale: AppLocale) => void;
  onPollIntervalChange: (pollIntervalSeconds: number) => void;
  onBackfillYearsChange: (backfillYears: number) => void;
  onHistorySweepAiCallLimitChange: (historySweepAiCallLimit: number) => void;
  onShortcutBindingsChange: (shortcutBindings: Record<string, ShortcutBindingSetting>) => void;
  onYoutubeTranscriptionModelChange: (model: string) => void;
  onYoutubeTranscriptionTimeoutChange: (timeoutSeconds: number) => void;
  onGeneralAnalysisProviderChange: (provider: string) => void;
  onGeneralAnalysisModelChange: (model: string) => void;
  onGeneralAnalysisTimeoutChange: (timeoutSeconds: number) => void;
  onEspiAiFallbackChange: (enabled: boolean) => void;
  onOpenAiCompatibleBaseUrlChange: (baseUrl: string) => void;
  onCapabilityProvidersChange: (capabilityProviders: Record<string, CapabilityProviderEntry[]>) => void;
  onLogLevelChange: (level: string) => void;
  onLogMaxFilesChange: (maxFiles: number) => void;
  onLogMaxFileBytesChange: (maxFileBytes: number) => void;
  onDbMaxConnectionsChange: (maxConnections: number) => void;
  onDbBusyTimeoutMsChange: (busyTimeoutMs: number) => void;
  onDbAcquireTimeoutMsChange: (acquireTimeoutMs: number) => void;
  onResetDatabaseSettings: () => void;
  onSourcesWorkersChange: (workers: number) => void;
  onAutopilotWorkersChange: (workers: number) => void;
  onAiWorkersChange: (workers: number) => void;
  onAiProviderConcurrencyChange: (concurrency: number) => void;
  onResetQueueSettings: () => void;
  onClearLicenseKey: () => void;
  onLicenseKeyDraftChange: (licenseKey: string) => void;
  onSubmitLicenseKey: (event: FormEvent<HTMLFormElement>) => void;
  onGeminiApiKeyDraftChange: (apiKey: string) => void;
  onSaveGeminiApiKey: (event: FormEvent<HTMLFormElement>) => void;
  onClearGeminiApiKey: () => void;
  onOpenGeminiApiKeyPage: () => void;
  onImportApplied: () => void;
  formatTimestamp: (value: string | null | undefined, emptyLabel?: string) => string;
  formatPollInterval: (seconds: number) => string;
  formatAiProvider: (value: string | null | undefined) => string;
  formatGeminiModel: (value: string | null | undefined) => string;
  formatCredentialConfigured: (status: CredentialStatus | null) => string;
  formatCredentialKind: (value: string | null | undefined) => string;
};
